//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUser.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BrandResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrandResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskUser.Resources.BrandResource", typeof(BrandResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_BrandManage {
            get {
                return ResourceManager.GetString("lbl_BrandManage", resourceCulture);
            }
        }
        
        public static string lbl_BrandName {
            get {
                return ResourceManager.GetString("lbl_BrandName", resourceCulture);
            }
        }
        
        public static string lbl_AddBrand {
            get {
                return ResourceManager.GetString("lbl_AddBrand", resourceCulture);
            }
        }
        
        public static string lbl_EditBrand {
            get {
                return ResourceManager.GetString("lbl_EditBrand", resourceCulture);
            }
        }
        
        public static string lbl_manipulation {
            get {
                return ResourceManager.GetString("lbl_manipulation", resourceCulture);
            }
        }
        
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        public static string btn_AreYouSureYouWantToDeleteIt_ {
            get {
                return ResourceManager.GetString("btn_AreYouSureYouWantToDeleteIt?", resourceCulture);
            }
        }
        
        public static string lbl_AddNewBrand {
            get {
                return ResourceManager.GetString("lbl_AddNewBrand", resourceCulture);
            }
        }
        
        public static string err_AddFailure {
            get {
                return ResourceManager.GetString("err_AddFailure", resourceCulture);
            }
        }
        
        public static string err_EditFailure {
            get {
                return ResourceManager.GetString("err_EditFailure", resourceCulture);
            }
        }
        
        public static string msg_NameBrandAlreadyExists {
            get {
                return ResourceManager.GetString("msg_NameBrandAlreadyExists", resourceCulture);
            }
        }
        
        public static string msg_NotEmpty {
            get {
                return ResourceManager.GetString("msg_NotEmpty", resourceCulture);
            }
        }
    }
}
