//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUser.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskUser.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string btn_Product {
            get {
                return ResourceManager.GetString("btn_Product", resourceCulture);
            }
        }
        
        public static string btn_Store {
            get {
                return ResourceManager.GetString("btn_Store", resourceCulture);
            }
        }
        
        public static string btn_Category {
            get {
                return ResourceManager.GetString("btn_Category", resourceCulture);
            }
        }
        
        public static string btn_User {
            get {
                return ResourceManager.GetString("btn_User", resourceCulture);
            }
        }
        
        public static string btn_Management {
            get {
                return ResourceManager.GetString("btn_Management", resourceCulture);
            }
        }
        
        public static string btn_Brand {
            get {
                return ResourceManager.GetString("btn_Brand", resourceCulture);
            }
        }
        
        public static string btn_Stock {
            get {
                return ResourceManager.GetString("btn_Stock", resourceCulture);
            }
        }
        
        public static string msg_DeleteSuccessfuly {
            get {
                return ResourceManager.GetString("msg_DeleteSuccessfuly", resourceCulture);
            }
        }
        
        public static string msg_AddSuccessfuly {
            get {
                return ResourceManager.GetString("msg_AddSuccessfuly", resourceCulture);
            }
        }
        
        public static string msg_EditSuccessfuly {
            get {
                return ResourceManager.GetString("msg_EditSuccessfuly", resourceCulture);
            }
        }
        
        public static string err_AddFailure {
            get {
                return ResourceManager.GetString("err_AddFailure", resourceCulture);
            }
        }
        
        public static string err_EditFailure {
            get {
                return ResourceManager.GetString("err_EditFailure", resourceCulture);
            }
        }
        
        public static string err_DeleteFailure {
            get {
                return ResourceManager.GetString("err_DeleteFailure", resourceCulture);
            }
        }
        
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        public static string btn_AreYouSureYouWantToDeleteIt_ {
            get {
                return ResourceManager.GetString("btn_AreYouSureYouWantToDeleteIt?", resourceCulture);
            }
        }
        
        public static string btn_GoBackToTheMainPage {
            get {
                return ResourceManager.GetString("btn_GoBackToTheMainPage", resourceCulture);
            }
        }
    }
}
