//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUser.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskUser.Resources.LoginResource", typeof(LoginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_SignIn {
            get {
                return ResourceManager.GetString("lbl_SignIn", resourceCulture);
            }
        }
        
        public static string lbl_Password {
            get {
                return ResourceManager.GetString("lbl_Password", resourceCulture);
            }
        }
        
        public static string lbl_UserName {
            get {
                return ResourceManager.GetString("lbl_UserName", resourceCulture);
            }
        }
        
        public static string btn_RememberMe {
            get {
                return ResourceManager.GetString("btn_RememberMe", resourceCulture);
            }
        }
        
        public static string btn_ForgotPassword_ {
            get {
                return ResourceManager.GetString("btn_ForgotPassword?", resourceCulture);
            }
        }
        
        public static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        public static string msg_LengthFrom1To100Characters {
            get {
                return ResourceManager.GetString("msg_LengthFrom1To100Characters", resourceCulture);
            }
        }
        
        public static string msg_EmailIsNotAvalidEmailAddress {
            get {
                return ResourceManager.GetString("msg_EmailIsNotAvalidEmailAddress", resourceCulture);
            }
        }
        
        public static string msg_NotEmpty {
            get {
                return ResourceManager.GetString("msg_NotEmpty", resourceCulture);
            }
        }
        
        public static string msg_MinimumLengthOf6Characters {
            get {
                return ResourceManager.GetString("msg_MinimumLengthOf6Characters", resourceCulture);
            }
        }
        
        public static string msg_PasswordMustContainBothLetterSandNumbers_ {
            get {
                return ResourceManager.GetString("msg_PasswordMustContainBothLetterSandNumbers.", resourceCulture);
            }
        }
        
        public static string msg_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("msg_EmailAlreadyExists", resourceCulture);
            }
        }
    }
}
