//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUser.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PasswordResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskUser.Resources.PasswordResource", typeof(PasswordResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_EditPassWord {
            get {
                return ResourceManager.GetString("lbl_EditPassWord", resourceCulture);
            }
        }
        
        public static string lbl_NewPassWord {
            get {
                return ResourceManager.GetString("lbl_NewPassWord", resourceCulture);
            }
        }
        
        public static string lbl_ConfirmPassWord {
            get {
                return ResourceManager.GetString("lbl_ConfirmPassWord", resourceCulture);
            }
        }
        
        public static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        public static string err_EditFailure {
            get {
                return ResourceManager.GetString("err_EditFailure", resourceCulture);
            }
        }
        
        public static string msg_EditPasswordSuccessfuly {
            get {
                return ResourceManager.GetString("msg_EditPasswordSuccessfuly", resourceCulture);
            }
        }
        
        public static string msg_NotEmpty {
            get {
                return ResourceManager.GetString("msg_NotEmpty", resourceCulture);
            }
        }
        
        public static string msg_MinimumLengthOf6Characters {
            get {
                return ResourceManager.GetString("msg_MinimumLengthOf6Characters", resourceCulture);
            }
        }
        
        public static string msg_PasswordMustContainBothLetterSandNumbers_ {
            get {
                return ResourceManager.GetString("msg_PasswordMustContainBothLetterSandNumbers.", resourceCulture);
            }
        }
        
        public static string msg_ThePasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("msg_ThePasswordDoesNotMatch", resourceCulture);
            }
        }
        
        public static string err_PasswordFailure {
            get {
                return ResourceManager.GetString("err_PasswordFailure", resourceCulture);
            }
        }
    }
}
