//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUser.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskUser.Resources.ProductResource", typeof(ProductResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_ProductManage {
            get {
                return ResourceManager.GetString("lbl_ProductManage", resourceCulture);
            }
        }
        
        public static string lbl_ProductName {
            get {
                return ResourceManager.GetString("lbl_ProductName", resourceCulture);
            }
        }
        
        public static string lbl_BrandId {
            get {
                return ResourceManager.GetString("lbl_BrandId", resourceCulture);
            }
        }
        
        public static string lbl_CategoryId {
            get {
                return ResourceManager.GetString("lbl_CategoryId", resourceCulture);
            }
        }
        
        public static string lbl_ModelYear {
            get {
                return ResourceManager.GetString("lbl_ModelYear", resourceCulture);
            }
        }
        
        public static string lbl_Picture {
            get {
                return ResourceManager.GetString("lbl_Picture", resourceCulture);
            }
        }
        
        public static string lbl_ListPrice {
            get {
                return ResourceManager.GetString("lbl_ListPrice", resourceCulture);
            }
        }
        
        public static string lbl_EditProduct {
            get {
                return ResourceManager.GetString("lbl_EditProduct", resourceCulture);
            }
        }
        
        public static string lbl_AddProduct {
            get {
                return ResourceManager.GetString("lbl_AddProduct", resourceCulture);
            }
        }
        
        public static string btn_AddNewProduct {
            get {
                return ResourceManager.GetString("btn_AddNewProduct", resourceCulture);
            }
        }
        
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        public static string lbl_manipulation {
            get {
                return ResourceManager.GetString("lbl_manipulation", resourceCulture);
            }
        }
        
        public static string btn_AreYouSureYouWantToDeleteIt_ {
            get {
                return ResourceManager.GetString("btn_AreYouSureYouWantToDeleteIt?", resourceCulture);
            }
        }
        
        public static string err_AddFailure {
            get {
                return ResourceManager.GetString("err_AddFailure", resourceCulture);
            }
        }
        
        public static string err_EditFailure {
            get {
                return ResourceManager.GetString("err_EditFailure", resourceCulture);
            }
        }
        
        public static string msg_NotEmpty {
            get {
                return ResourceManager.GetString("msg_NotEmpty", resourceCulture);
            }
        }
    }
}
