//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUser.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoreResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskUser.Resources.StoreResource", typeof(StoreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_StoreName {
            get {
                return ResourceManager.GetString("lbl_StoreName", resourceCulture);
            }
        }
        
        public static string lbl_AddStore {
            get {
                return ResourceManager.GetString("lbl_AddStore", resourceCulture);
            }
        }
        
        public static string lbl_EditStore {
            get {
                return ResourceManager.GetString("lbl_EditStore", resourceCulture);
            }
        }
        
        public static string lbl_Edit {
            get {
                return ResourceManager.GetString("lbl_Edit", resourceCulture);
            }
        }
        
        public static string btn_AddNewStore {
            get {
                return ResourceManager.GetString("btn_AddNewStore", resourceCulture);
            }
        }
        
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        public static string lbl_Phone {
            get {
                return ResourceManager.GetString("lbl_Phone", resourceCulture);
            }
        }
        
        public static string lbl_Street {
            get {
                return ResourceManager.GetString("lbl_Street", resourceCulture);
            }
        }
        
        public static string lbl_City {
            get {
                return ResourceManager.GetString("lbl_City", resourceCulture);
            }
        }
        
        public static string lbl_State {
            get {
                return ResourceManager.GetString("lbl_State", resourceCulture);
            }
        }
        
        public static string lbl_Zipcode {
            get {
                return ResourceManager.GetString("lbl_Zipcode", resourceCulture);
            }
        }
        
        public static string lbl_manipulation {
            get {
                return ResourceManager.GetString("lbl_manipulation", resourceCulture);
            }
        }
        
        public static string lbl_StoreManage {
            get {
                return ResourceManager.GetString("lbl_StoreManage", resourceCulture);
            }
        }
        
        public static string btn_AreYouSureYouWantToDeleteIt_ {
            get {
                return ResourceManager.GetString("btn_AreYouSureYouWantToDeleteIt?", resourceCulture);
            }
        }
        
        public static string err_AddFailure {
            get {
                return ResourceManager.GetString("err_AddFailure", resourceCulture);
            }
        }
        
        public static string err_EditFailure {
            get {
                return ResourceManager.GetString("err_EditFailure", resourceCulture);
            }
        }
        
        public static string msg_LengthFrom1To100Characters {
            get {
                return ResourceManager.GetString("msg_LengthFrom1To100Characters", resourceCulture);
            }
        }
        
        public static string msg_EmailIsNotAvalidEmailAddress {
            get {
                return ResourceManager.GetString("msg_EmailIsNotAvalidEmailAddress", resourceCulture);
            }
        }
        
        public static string msg_NotEmpty {
            get {
                return ResourceManager.GetString("msg_NotEmpty", resourceCulture);
            }
        }
        
        public static string msg_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("msg_EmailAlreadyExists", resourceCulture);
            }
        }
    }
}
