//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUser.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskUser.Resources.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_UserManage {
            get {
                return ResourceManager.GetString("lbl_UserManage", resourceCulture);
            }
        }
        
        public static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        public static string lbl_IsActiver {
            get {
                return ResourceManager.GetString("lbl_IsActiver", resourceCulture);
            }
        }
        
        public static string lbl_AddUser {
            get {
                return ResourceManager.GetString("lbl_AddUser", resourceCulture);
            }
        }
        
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        public static string lbl_Password {
            get {
                return ResourceManager.GetString("lbl_Password", resourceCulture);
            }
        }
        
        public static string lbl_Phone {
            get {
                return ResourceManager.GetString("lbl_Phone", resourceCulture);
            }
        }
        
        public static string lbl_StoreId {
            get {
                return ResourceManager.GetString("lbl_StoreId", resourceCulture);
            }
        }
        
        public static string btn_AddNewUser {
            get {
                return ResourceManager.GetString("btn_AddNewUser", resourceCulture);
            }
        }
        
        public static string lbl_EditUser {
            get {
                return ResourceManager.GetString("lbl_EditUser", resourceCulture);
            }
        }
        
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        public static string lbl_manipulation {
            get {
                return ResourceManager.GetString("lbl_manipulation", resourceCulture);
            }
        }
        
        public static string err_AddFailure {
            get {
                return ResourceManager.GetString("err_AddFailure", resourceCulture);
            }
        }
        
        public static string err_EditFailure {
            get {
                return ResourceManager.GetString("err_EditFailure", resourceCulture);
            }
        }
        
        public static string msg_LengthFrom1To100Characters {
            get {
                return ResourceManager.GetString("msg_LengthFrom1To100Characters", resourceCulture);
            }
        }
        
        public static string msg_EmailIsNotAvalidEmailAddress {
            get {
                return ResourceManager.GetString("msg_EmailIsNotAvalidEmailAddress", resourceCulture);
            }
        }
        
        public static string msg_NotEmpty {
            get {
                return ResourceManager.GetString("msg_NotEmpty", resourceCulture);
            }
        }
        
        public static string msg_MinimumLengthOf6Characters {
            get {
                return ResourceManager.GetString("msg_MinimumLengthOf6Characters", resourceCulture);
            }
        }
        
        public static string msg_PasswordMustContainBothLetterSandNumbers_ {
            get {
                return ResourceManager.GetString("msg_PasswordMustContainBothLetterSandNumbers.", resourceCulture);
            }
        }
        
        public static string msg_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("msg_EmailAlreadyExists", resourceCulture);
            }
        }
    }
}
